### ISSUE TITLE
Should not accept "💩.💩.💩.💩" as a valid IP address.

### ISSUE THREAD

**Issue by masonmark** [CautemocSg/ng-ip-address#5]
"💩.💩.💩.💩" is not a valid IP address. However, it can be pasted, or even typed, into an `ng-ip-address` text input field and validation will pass.

I also noticed strings like `23s.23s.23d.23d` can be pasted in, although typing them in manually is prevented.

**Comment by CautemocSg** [comment]
Bug confirmed. Working on the validation.

I haven't implemented clipboard scraping and formatting yet, it was on my to do list along with IPv6 support but I got caught up with some other things.

**Comment by CautemocSg** [comment]
Validation resolved in version [1.1.12](https://github.com/CautemocSg/ng-ip-address/releases/tag/v1.1.12).
